# Generated by Django 4.1.7 on 2023-04-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('card_id', models.AutoField(default=100001, primary_key=True, serialize=False, unique=True, verbose_name='Картка №')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('blood_group', models.CharField(max_length=20, verbose_name='Група крові')),
                ('traumas_info', models.CharField(max_length=5000, verbose_name='Травми')),
                ('operations_info', models.CharField(max_length=5000, verbose_name='Операції')),
                ('chronical_illness_info', models.CharField(max_length=5000, verbose_name='Хронічні захворювання')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
