# Generated by Django 4.1.7 on 2023-04-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_media'),
        ('patientcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='card_id',
            field=models.AutoField(default=808889, primary_key=True, serialize=False, unique=True, verbose_name='Картка №'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='users.patient'),
        ),
    ]
