# Generated by Django 4.1.7 on 2023-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientcard', '0002_alter_patientcard_card_id_alter_patientcard_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='card_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Картка №'),
        ),
    ]
