# Generated by Django 4.1.7 on 2023-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дата народження'),
        ),
    ]
