# Generated by Django 4.1.7 on 2023-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(blank=True, default=0, verbose_name='Чи є лікарем'),
        ),
    ]
