# Generated by Django 4.1.7 on 2023-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(default='2023-04-20', verbose_name='Дата створення'),
        ),
    ]
