# Generated by Django 4.1.7 on 2023-04-17 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='doctor_profile_photo/default_image.png', upload_to='doctor_profile_photo', verbose_name='Фото профіля')),
                ('price', models.IntegerField(verbose_name='Вартість прийому')),
                ('experience', models.CharField(max_length=20, verbose_name='Стаж')),
                ('category', models.CharField(max_length=30, verbose_name='Категорія')),
                ('info', models.CharField(blank=True, max_length=1000, verbose_name='Загальна нформація про лікаря')),
                ('education', models.CharField(default='', max_length=1000, verbose_name='Освіта')),
                ('courses', models.CharField(blank=True, default='', max_length=1000, verbose_name='Курси')),
                ('procedures_performed', models.CharField(blank=True, default='', max_length=1000, verbose_name='Виконувані процедури')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Дерматолог', 'Дерматолог'), ('Кардіолог', 'Кардіолог'), ('Пульмонолог', 'Пульмонолог'), ('Нейрологія', 'Нейрологія'), ('Терапевт', 'Терапевт'), ('Гастроентеролог', 'Гастроентеролог')], default='Не обрано', max_length=30)),
                ('image', models.FileField(default='Cardiologist.svg', upload_to='specialization_images', verbose_name='Зображення спеціальності')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUnavailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30')], default='09:00', max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_time', to='users.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='specialization', to='users.specialization'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30')], default='09:00', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=15)),
                ('medical_history', models.CharField(blank=True, default='', max_length=1000, verbose_name='Анамнез захворювання')),
                ('objective_status', models.CharField(blank=True, default='', max_length=1000, verbose_name="Об'єктивний статус")),
                ('diagnosis', models.CharField(blank=True, default='', max_length=500, verbose_name='Діагноз')),
                ('examination', models.CharField(blank=True, default='', max_length=1000, verbose_name='Обстеження')),
                ('recommendations', models.CharField(blank=True, default='', max_length=1000, verbose_name='Рекомендації')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
    ]
