# Generated by Django 4.1.7 on 2023-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.CharField(default='Вища', max_length=30, verbose_name='Категорія'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(default='10 років', max_length=20, verbose_name='Стаж'),
            preserve_default=False,
        ),
    ]
