# Generated by Django 4.1.7 on 2023-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Активний', 'Активний'), ('Завершений', 'Завершений')], default='Активний', max_length=15),
        ),
    ]
