# Generated by Django 4.1.7 on 2023-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=0, verbose_name='Прийнятий лікарем'),
        ),
    ]
