# Generated by Django 4.1.7 on 2023-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appointment_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Непідтверджений', 'Непідтверджений'), ('Активний', 'Активний'), ('Завершений', 'Завершений')], default='Непідтверджений', max_length=15),
        ),
    ]
