# Generated by Django 4.1.7 on 2023-04-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment_status_alter_doctor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='doctors_profile_images'),
        ),
    ]
