# Generated by Django 4.1.7 on 2023-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_appointment_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(choices=[('Дерматолог', 'Дерматолог'), ('Кардіолог', 'Кардіолог'), ('Пульмонолог', 'Пульмонолог'), ('Невролог', 'Невролог'), ('Терапевт', 'Терапевт'), ('Гастроентеролог', 'Гастроентеролог')], default='Не обрано', max_length=30),
        ),
    ]
