# Generated by Django 4.1.7 on 2023-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Активний', 'Активний'), ('Завершений', 'Завершений'), ('Скасований', 'Скасований')], default='Активний', max_length=15),
        ),
    ]
