# Generated by Django 4.1.7 on 2023-04-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appointment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'patient', 'day', 'time')},
        ),
    ]
