# Generated by Django 4.1.7 on 2023-04-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'day', 'time')},
        ),
    ]
